In [2]:
from sklearn.preprocessing import MinMaxScaler

Scaler = MinMaxScaler()
data = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]  # Fixed missing comma
scaled_data = Scaler.fit_transform(data)
print(scaled_data)


[[0.  0.  0. ]
 [0.5 0.5 0.5]
 [1.  1.  1. ]]


In [10]:
import numpy as np
from sklearn.impute import SimpleImputer
Imputer=SimpleImputer(strategy="mean")
data=[[1,np.nan,3],[4,np.nan,5],[6,7,np.nan]]
scaled_data=Imputer.fit_transform(data)
print(scaled_data)

[[1. 7. 3.]
 [4. 7. 5.]
 [6. 7. 4.]]


In [9]:
from sklearn.impute import KNNImputer
#transformer..we are importing KNN imputer from sklearn.impute module
import numpy as np
imputer=KNNImputer(n_neighbors=3)#defining KNNImputer instance withe the name_imputer
#with number of neighbors=2
x=[[1,2,np.nan],[3,4,3],[np.nan,6,5],[8,8,7]]#this is our target matrix
#as well as we apply
imputer.fit_transform(x)#

array([[1., 2., 5.],
       [3., 4., 3.],
       [4., 6., 5.],
       [8., 8., 7.]])

In [5]:
#Scaling
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
data=[[1,2,3],[4,5,6],[7,8,9]]
data1=scaler.fit_transform(data)
print(data1)



[[-1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487]]


In [7]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
data=[[-1,2],[-0.5,6],[0,10],[1,18]]
data1=scaler.fit_transform(data)
print(data1)

[[0.   0.  ]
 [0.25 0.25]
 [0.5  0.5 ]
 [1.   1.  ]]


In [9]:
from sklearn.preprocessing import MaxAbsScaler
scaler=MaxAbsScaler()
data=[[1,2,3],[4,5,6],[7,8,9]]
data1=scaler.fit_transform(data)
print(data1)

[[0.14285714 0.25       0.33333333]
 [0.57142857 0.625      0.66666667]
 [1.         1.         1.        ]]


In [11]:
from sklearn.preprocessing import OrdinalEncoder
encoder=OrdinalEncoder()
data=[['Pandi'],['kabilesh'],['harshini'],['Anandan']]
result=encoder.fit_transform(data)
result

array([[1.],
       [3.],
       [2.],
       [0.]])